Fix MGF issues
perl-net-saml2/perl-XML-Enc pull request #4
Opened 2023-03-12 22:42 UTC by timlegge

libtom (CryptX <= 0.077) does not support specifying the a MGF and OEAPparam digest that differ.

This sorts out most of the issues.  Thinking now I suspect that it will still allow you to generate XML that will not properly decrypt but basically, the two must use the same hash in both

2023-03-30 15:31 UTC, waterkip requested changes

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +    return if ! defined $method;
Same exists logic.

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +    return if ! defined $method;
Same exists logic.

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +    return if ! defined $method;
You do an exists later on, shouldn't it either croak/die/warn about method not being specified or use the default which is used later on?

So, method having value `''` or `0` is fine, but `undef` isn't. I would perhaps do `$method //= ''`; and continue with the function. Or just `croak` if it is `undef`.

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +    return if ! defined $method;
Same exists logic.

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +        if ($method{Algorithm} eq 'http://www.w3.org/2009/xmlenc11#rsa-oaep') {
L511-519 and 529-540 are the same. Perhaps make a function for it?

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +        my $oaep_params = defined $keymethod->{OAEPparams} ?
This is also almost the same as the additions starting at 652.

2023-03-30 15:31 UTC, waterkip commented on lib/XML/Enc.pm
> +        my $oaep_label_hash = (defined $self->{oaep_label_hash} && $self->{oaep_label_hash} ne '') ?
683 and below matches 692 and below as well.

2024-12-27 15:33 UTC, timlegge commented
Closing in favour of #12 which is a rebase and seems to fix most of these issues

2024-12-27 15:33 UTC, closed without merging